openapi: 3.0.0
info:
  title: TP final CDA Node Maximilien
  description: Cette API permet de gérer des films.
  version: "1.0.0"
servers:
  - url: http://localhost:3000
paths:
  /movies:
   get:
    summary: Liste de tous les films
    responses:
      '200':
        description: Une liste de tous les films
        content:
          text/plain:
            schema:
              type: array
              items:
                $ref: './src/domain/entities/Movies.ts'
              example: 
                - id: 1
                  title: "Film 1"
                  year: 2022
                - id: 2
                  title: "Film 2"
                  year: 2023