openapi: 3.0.0
info:
  title: TP final CDA Node Maximilien
  description: Cette API permet de gérer des films.
  version: "1.0.0"
servers:
  - url: http://localhost:3000
paths:
  /:
   get:
    summary:
    responses:
      '200':
        description: Hello World
        content:
          text/plain:
            schema:
              type: string
              example: Hello World